CREATE TABLE credit_products_db.USER_CREDIT_SCORE (
    CREDIT_ID VARCHAR(200) NOT NULL,
    USER_ID VARCHAR(200) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_TIME TIMESTAMP NOT NULL,
    constraint CREDIT_ID_PK primary key (CREDIT_ID)
 );