spring:
  application:
    name: credit-score-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    default-schema: credit_products_db_score
    baselineOnMigrate: true
  locations:
    - classpath:db/migration

server:
  port: 8092

management:
  endpoints:
    web:
      exposure:
        include: "*"