spring:
  application:
    name: workflow-engine
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

camunda.bpm.admin-user:
  id: demo
  password: demo

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus